config/routes.rb
Rails.application.routes.draw do
  root to: "lists#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, except: [ :edit, :update, :destroy ] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, uniqueness: { scope: :list }
  # validates :movie, presence: true
  # validates :list, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
    @bookmarks = @list.bookmarks
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="form-row">
    <div class="card-form">
      <h2>Add a movie to your <%= @list.name %>-list </h2>
      <div class="form-group">
        <%= simple_form_for [ @list, @bookmark ] do |f| %>
          <%= f.association :movie %>
          <%= f.input :comment %>
          <%= f.submit "Add movie", class: "btn btn-outline-dark"%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar fixed-top bg-dark">
      <form class="container-fluid justify-content-end">
      <%= link_to 'My Lists', lists_path, class: "btn btn-outline-light"  %>
      </form>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="banner banner-hp" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1478720568477-152d9b164e26?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80);">
  <div class="container">
    <h1>These are all your movie lists!</h1>
    <p>Make watch-lists easy</p>
    <%= link_to 'Make new List', new_list_path, class: "btn btn-outline-light" %>
  </div>
</div>
<div class="container">
  <div class="row ml-1 justify-content-start">
    <% @lists.each do |list|  %>
      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 mb-3">
        <% if list.photo.attached? %>
          <% url = cl_image_path list.photo.key, height: 300, crop: :fill %>
        <% else %>
          <% url = 'https://source.unsplash.com/random/?cinema' %>
        <% end %>
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)),  url('<%= url %>')">
          <%= link_to list.name, list_path(list) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="form-row">
    <div class="card-form">
      <h2>Create a new list</h2>
      <div class="form-group">
        <%= simple_form_for(@list) do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :file %>
          <%= f.submit "Create list", class: "btn btn-outline-dark" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/show.html.erb
<% if @list.photo.attached? %>
  <% url = cl_image_path @list.photo.key, class: "img-banner" %>
<% else %>
  <% url = 'https://source.unsplash.com/random/?cinema' %>
<% end %>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= url %>');">
  <div class="container">
    <h1><%= @list.name %></h1>
    <%= link_to 'Add movies', new_list_bookmark_path(@list), class: "btn btn-outline-light" %>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="col-9  mb-3">
        <div class="card-product">
          <img src=  <%= bookmark.movie.poster_url %> >
          <div class="card-product-infos">
            <h2><%= bookmark.movie.title %></h2>
            <p><%= bookmark.movie.overview.truncate(250, separator: ' ', omission: '... (continued)') %></p>
            <p class="comment"><%= bookmark.comment %></p>
            <div class="delete" data-toggle="tooltip" data-placement="top" title="Remove from list">
              <%= link_to '<svg xmlns="http://www.w3.org/2000/svg" width="auto" height="auto" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                          </svg>'.html_safe, bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure?" }  %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>